print("Student Form")
print("--------------")
name = input("Please Enter your Name: ")
age = int(input("Please Enter your Age: "))
course = input ("Please Enter your Course: ")
section = input ("Please Enter your Section: ")
year = input ("Please Enter your Year: ")
motto = input("Motto in Life?: ")
print("-----------------------------------")
print("Student Information")
print("-------------------")
print("Name: ",name)
print("Age: ",age)
print("Course: ",course)
print("Year and Section: ",year, "- Section",section)
print("Motto :", motto)
